【Date】2023/09/11 15:47:33【Exe】ConsoleApp_Download.exe【Source】Module_Download【Method】InsertTRNLOG【Description】SQL実行時エラー: INSERT INTO TRN_LOG(             PROCESS_DATE,             MACHINE_NO,             PROCESS_TIME,             FILE_NAME,             ACHIEVEMENT_RECEIVE_TIME,             ACHIEVEMENT_RESULT,             NOTE,             CREATE_DATE,             UPDATE_DATE ) VALUES(     '2023-09-11 15:47:33',     '1',     '15:47:33',     '40TR0001.CSV',     '15:47:33',     'NG',     '列 12 が見つかりません。',     '2023/09/11 15:47:33',     '2023/09/11 15:47:33' )
【Date】2023/09/11 15:47:46【Exe】ConsoleApp_Download.exe【Source】Module_Download【Method】DelUploadFtp【Description】ファイル 'C:\Users\1233\Desktop\remote-repo\KANSAI_ISHIDA_SANPAI\CSV\40TR0001.DEL' が見つかりませんでした。
【Date】2023/09/11 15:49:03【Exe】ConsoleApp_Download.exe【Source】Module_Download【Method】InsertTRNLOG【Description】SQL実行時エラー: INSERT INTO TRN_LOG(             PROCESS_DATE,             MACHINE_NO,             PROCESS_TIME,             FILE_NAME,             ACHIEVEMENT_RECEIVE_TIME,             ACHIEVEMENT_RESULT,             NOTE,             CREATE_DATE,             UPDATE_DATE ) VALUES(     '2023-09-11 15:49:03',     '1',     '15:49:03',     '40TR0001.CSV',     '15:49:03',     'NG',     '列 12 が見つかりません。',     '2023/09/11 15:49:03',     '2023/09/11 15:49:03' )
【Date】2023/09/11 15:49:08【Exe】ConsoleApp_Download.exe【Source】Module_Download【Method】DelUploadFtp【Description】ファイル 'C:\Users\1233\Desktop\remote-repo\KANSAI_ISHIDA_SANPAI\CSV\40TR0001.DEL' が見つかりませんでした。
【Date】2023/09/11 15:51:41【Exe】ConsoleApp_Download.exe【Source】Module_Download【Method】InsertTRNLOG【Description】SQL実行時エラー: INSERT INTO TRN_LOG(             PROCESS_DATE,             MACHINE_NO,             PROCESS_TIME,             FILE_NAME,             ACHIEVEMENT_RECEIVE_TIME,             ACHIEVEMENT_RESULT,             NOTE,             CREATE_DATE,             UPDATE_DATE ) VALUES(     '2023-09-11 15:51:41',     '1',     '15:51:41',     '40TR0001.CSV',     '15:51:41',     'NG',     '列 12 が見つかりません。',     '2023/09/11 15:51:41',     '2023/09/11 15:51:41' )
【Date】2023/09/11 15:51:46【Exe】ConsoleApp_Download.exe【Source】Module_Download【Method】DelUploadFtp【Description】ファイル 'C:\Users\1233\Desktop\remote-repo\KANSAI_ISHIDA_SANPAI\CSV\40TR0001.DEL' が見つかりませんでした。
【Date】2023/09/11 15:54:23【Exe】ConsoleApp_Download.exe【Source】Module_Download【Method】InsertTRNLOG【Description】SQL実行時エラー: INSERT INTO TRN_LOG(             PROCESS_DATE,             MACHINE_NO,             PROCESS_TIME,             FILE_NAME,             ACHIEVEMENT_RECEIVE_TIME,             ACHIEVEMENT_RESULT,             NOTE,             CREATE_DATE,             UPDATE_DATE ) VALUES(     '2023-09-11 15:54:23',     '1',     '15:54:23',     '40TR0001.CSV',     '15:54:23',     'NG',     '列 12 が見つかりません。',     '2023/09/11 15:54:23',     '2023/09/11 15:54:23' )
【Date】2023/09/11 15:54:23【Exe】ConsoleApp_Download.exe【Source】Module_Download【Method】DelUploadFtp【Description】ファイル 'C:\Users\1233\Desktop\remote-repo\KANSAI_ISHIDA_SANPAI\CSV\40TR0001.DEL' が見つかりませんでした。
【Date】2023/09/11 15:56:50【Exe】ConsoleApp_Download.exe【Source】Module_Download【Method】InsertTRNLOG【Description】SQL実行時エラー: INSERT INTO TRN_LOG(             PROCESS_DATE,             MACHINE_NO,             PROCESS_TIME,             FILE_NAME,             ACHIEVEMENT_RECEIVE_TIME,             ACHIEVEMENT_RESULT,             NOTE,             CREATE_DATE,             UPDATE_DATE ) VALUES(     '2023-09-11 15:56:50',     '1',     '15:56:50',     '40TR0001.CSV',     '15:56:50',     'NG',     'リモート サーバーがエラーを返しました: (421) サービスが使用できません。管理接続を閉じています',     '2023/09/11 15:56:50',     '2023/09/11 15:56:50' )
【Date】2023/09/11 15:57:11【Exe】ConsoleApp_Download.exe【Source】Module_Download【Method】InsertTRNLOG【Description】SQL実行時エラー: INSERT INTO TRN_LOG(             PROCESS_DATE,             MACHINE_NO,             PROCESS_TIME,             FILE_NAME,             ACHIEVEMENT_RECEIVE_TIME,             ACHIEVEMENT_RESULT,             NOTE,             CREATE_DATE,             UPDATE_DATE ) VALUES(     '2023-09-11 15:57:11',     '1',     '15:57:11',     '40TR0001.CSV',     '15:57:11',     'NG',     '列 12 が見つかりません。',     '2023/09/11 15:57:11',     '2023/09/11 15:57:11' )
【Date】2023/09/11 15:58:03【Exe】ConsoleApp_Download.exe【Source】Module_Download【Method】InsertTRNLOG【Description】SQL実行時エラー: INSERT INTO TRN_LOG(             PROCESS_DATE,             MACHINE_NO,             PROCESS_TIME,             FILE_NAME,             ACHIEVEMENT_RECEIVE_TIME,             ACHIEVEMENT_RESULT,             NOTE,             CREATE_DATE,             UPDATE_DATE ) VALUES(     '2023-09-11 15:58:03',     '1',     '15:58:03',     '40TR0001.CSV',     '15:58:03',     'NG',     '別のプロセスで使用されているため、プロセスはファイル 'C:\Users\1233\Desktop\remote-repo\KANSAI_ISHIDA_SANPAI\DOWNLOAD\Unit1\40TR0001.CSV' にアクセスできません。',     '2023/09/11 15:58:03',     '2023/09/11 15:58:03' )
【Date】2023/09/11 15:58:21【Exe】ConsoleApp_Download.exe【Source】Module_Download【Method】InsertTRNLOG【Description】SQL実行時エラー: INSERT INTO TRN_LOG(             PROCESS_DATE,             MACHINE_NO,             PROCESS_TIME,             FILE_NAME,             ACHIEVEMENT_RECEIVE_TIME,             ACHIEVEMENT_RESULT,             NOTE,             CREATE_DATE,             UPDATE_DATE ) VALUES(     '2023-09-11 15:58:21',     '1',     '15:58:21',     '40TR0001.CSV',     '15:58:21',     'NG',     '列 12 が見つかりません。',     '2023/09/11 15:58:21',     '2023/09/11 15:58:21' )
【Date】2023/09/11 16:07:40【Exe】ConsoleApp_Download.exe【Source】Module_Download【Method】InsertTRNLOG【Description】SQL実行時エラー: INSERT INTO TRN_LOG(             PROCESS_DATE,             MACHINE_NO,             PROCESS_TIME,             FILE_NAME,             ACHIEVEMENT_RECEIVE_TIME,             ACHIEVEMENT_RESULT,             NOTE,             CREATE_DATE,             UPDATE_DATE ) VALUES(     '2023-09-11 16:07:40',     '1',     '16:07:40',     '40TR0001.CSV',     '16:07:40',     'NG',     'String "kg" から型 'Double' への変換は無効です。',     '2023/09/11 16:07:40',     '2023/09/11 16:07:40' )
【Date】2023/09/11 16:22:43【Exe】ConsoleApp_Download.exe【Source】Module_Download【Method】InsertResultTable【Description】SQL実行時エラー: INSERT INTO RESULTS(             MACHINE_NO,             PROCESS_DATE,             PROCESS_TIME,             TENANT_CODE,             GARBAGE_CODE,             PACKING_COUNT,             PACKING_WEIGHT,             MEASURING_COUNT,             MEASURING_WEIGHT,             MODIFYING_FLG,             MANIFEST_FLG,             PROCESS_PRICE,             TOTAL_PRICE,             MEMO,             CREATE_DATE,             UPDATE_DATE ) VALUES(     '2023/09/11',     '15:57:10',     '000001',     '00000002',     '0.000',     '0',     '0.524',     '0',     '5000',     '',     '',     '2620',     '0.000',     '',     '2023/09/11 16:21:56',     '2023/09/11 16:21:56' )
【Date】2023/09/11 16:22:43【Exe】ConsoleApp_Download.exe【Source】Module_Download【Method】InsertTRNLOG【Description】SQL実行時エラー: INSERT INTO TRN_LOG(             PROCESS_DATE,             MACHINE_NO,             PROCESS_TIME,             FILE_NAME,             ACHIEVEMENT_RECEIVE_TIME,             ACHIEVEMENT_RESULT,             NOTE,             CREATE_DATE,             UPDATE_DATE ) VALUES(     '2023-09-11 16:22:43',     '1',     '16:22:43',     '40TR0001.CSV',     '16:22:43',     'OK',     '226 226 Transfer complete.
',     '2023/09/11 16:22:43',     '2023/09/11 16:22:43' )
【Date】2023/09/11 16:29:39【Exe】ConsoleApp_Download.exe【Source】Module_Download【Method】InsertTRNLOG【Description】SQL実行時エラー: INSERT INTO TRN_LOG(             PROCESS_DATE,             MACHINE_NO,             PROCESS_TIME,             FILE_NAME,             ACHIEVEMENT_RECEIVE_TIME,             ACHIEVEMENT_RESULT,             NOTE,             CREATE_DATE,             UPDATE_DATE ) VALUES(     '2023-09-11 16:29:39',     '1',     '16:29:39',     '40TR0001.CSV',     '16:29:39',     'OK',     '226 226 Transfer complete.
',     '2023/09/11 16:29:39',     '2023/09/11 16:29:39' )
【Date】2023/09/11 16:30:51【Exe】ConsoleApp_Download.exe【Source】Module_Download【Method】InsertTRNLOG【Description】SQL実行時エラー: INSERT INTO TRN_LOG(             PROCESS_DATE,             MACHINE_NO,             PROCESS_TIME,             FILE_NAME,             ACHIEVEMENT_RECEIVE_TIME,             ACHIEVEMENT_RESULT,             NOTE,             CREATE_DATE,             UPDATE_DATE ) VALUES(     '2023-09-11 16:30:51',     '1',     '16:30:51',     '40TR0001.CSV',     '16:30:51',     'OK',     '226 226 Transfer complete.
',     '2023/09/11 16:30:51',     '2023/09/11 16:30:51' )
【Date】2023/09/11 16:35:30【Exe】ConsoleApp_Download.exe【Source】Module_Download【Method】InsertTRNLOG【Description】SQL実行時エラー: INSERT INTO TRN_LOG(             PROCESS_DATE,             MACHINE_NO,             PROCESS_TIME,             FILE_NAME,             ACHIEVEMENT_RECEIVE_TIME,             ACHIEVEMENT_RESULT,             NOTE,             CREATE_DATE,             UPDATE_DATE ) VALUES(     '2023-09-11 16:35:30',     '1',     '16:35:30',     '40TR0001.CSV',     '16:35:30',     'OK',     '226 226 Transfer complete.
',     '2023/09/11 16:35:30',     '2023/09/11 16:35:30' )
【Date】2023/09/11 17:43:23【Exe】ConsoleApp_Download.exe【Source】Module_Download【Method】InsertTRNLOG【Description】SQL実行時エラー: INSERT INTO TRN_LOG(             PROCESS_DATE,             MACHINE_NO,             PROCESS_TIME,             FILE_NAME,             ACHIEVEMENT_RECEIVE_TIME,             ACHIEVEMENT_RESULT,             NOTE,             CREATE_DATE,             UPDATE_DATE ) VALUES(     '2023-09-11',     '1',     '17:43:20',     '40TR0001.CSV',     '17:43:20',     'False',     'リモート サーバーがエラーを返しました: (421) サービスが使用できません。管理接続を閉じています',     '2023/09/11 17:43:20',     '2023/09/11 17:43:20' )
【Date】2023/09/12 08:59:46【Exe】ConsoleApp_Download.exe【Source】Module_Download【Method】DelUploadFtp【Description】リモート サーバーがエラーを返しました: (421) サービスが使用できません。管理接続を閉じています
【Date】2023/09/12 09:03:05【Exe】ConsoleApp_Download.exe【Source】Module_Download【Method】InsertTRNLOG【Description】SQL実行時エラー: INSERT INTO TRN_LOG(             PROCESS_DATE,             MACHINE_NO,             PROCESS_TIME,             FILE_NAME,             ACHIEVEMENT_RECEIVE_TIME,             ACHIEVEMENT_RESULT,             NOTE,             CREATE_DATE,             UPDATE_DATE ) VALUES(     '2023-09-12',     '1',     '09:03:03',     '40TR0001.CSV',     '09:03:03',     'False',     'リモート サーバーがエラーを返しました: (421) サービスが使用できません。管理接続を閉じています',     '2023/09/12 9:03:03',     '2023/09/12 9:03:03' )
【Date】2023/09/12 13:50:20【Exe】ConsoleApp_Download.exe【Source】Module_Download【Method】InsertTRNLOG【Description】SQL実行時エラー: INSERT INTO TRN_LOG(             PROCESS_DATE,             MACHINE_NO,             PROCESS_TIME,             FILE_NAME,             ACHIEVEMENT_RECEIVE_TIME,             ACHIEVEMENT_RESULT,             NOTE,             CREATE_DATE,             UPDATE_DATE ) VALUES(     '2023-09-12',     '1',     '13:50:20',     '40TR0001.CSV',     '2023-09-12 13:50:20',     'False',     'リモート サーバーがエラーを返しました: (421) サービスが使用できません。管理接続を閉じています',     '2023/09/12 13:50:20',     '2023/09/12 13:50:20' )
【Date】2023/09/12 13:51:32【Exe】ConsoleApp_Download.exe【Source】Module_Download【Method】InsertTRNLOG【Description】SQL実行時エラー: INSERT INTO TRN_LOG(             PROCESS_DATE,             MACHINE_NO,             PROCESS_TIME,             FILE_NAME,             ACHIEVEMENT_RECEIVE_TIME,             ACHIEVEMENT_RESULT,             NOTE,             CREATE_DATE,             UPDATE_DATE ) VALUES(     '2023-09-12',     '1',     '13:51:30',     '40TR0001.CSV',     '2023-09-12 13:51:30',     'False',     'リモート サーバーがエラーを返しました: (421) サービスが使用できません。管理接続を閉じています',     '2023/09/12 13:51:30',     '2023/09/12 13:51:30' )
【Date】2023/09/12 13:51:45【Exe】ConsoleApp_Download.exe【Source】Module_Download【Method】InsertTRNLOG【Description】SQL実行時エラー: INSERT INTO TRN_LOG(             PROCESS_DATE,             MACHINE_NO,             PROCESS_TIME,             FILE_NAME,             ACHIEVEMENT_RECEIVE_TIME,             ACHIEVEMENT_RESULT,             NOTE,             CREATE_DATE,             UPDATE_DATE ) VALUES(     '2023-09-12',     '1',     '13:51:39',     '40TR0001.CSV',     '2023-09-12 13:51:39',     'False',     'リモート サーバーがエラーを返しました: (421) サービスが使用できません。管理接続を閉じています',     '2023/09/12 13:51:39',     '2023/09/12 13:51:39' )
【Date】2023/09/12 13:52:50【Exe】ConsoleApp_Download.exe【Source】Module_Download【Method】InsertTRNLOG【Description】SQL実行時エラー: INSERT INTO TRN_LOG(             PROCESS_DATE,             MACHINE_NO,             PROCESS_TIME,             FILE_NAME,             ACHIEVEMENT_RECEIVE_TIME,             ACHIEVEMENT_RESULT,             NOTE,             CREATE_DATE,             UPDATE_DATE ) VALUES(     '2023-09-12',     '1',     '13:52:49',     '40TR0001.CSV',     '2023-09-12 13:52:49',     'False',     'リモート サーバーがエラーを返しました: (421) サービスが使用できません。管理接続を閉じています',     '2023/09/12 13:52:49',     '2023/09/12 13:52:49' )
【Date】2023/09/12 13:53:52【Exe】ConsoleApp_Download.exe【Source】Module_Download【Method】InsertTRNLOG【Description】SQL実行時エラー: INSERT INTO TRN_LOG(             PROCESS_DATE,             MACHINE_NO,             PROCESS_TIME,             FILE_NAME,             ACHIEVEMENT_RECEIVE_TIME,             ACHIEVEMENT_RESULT,             NOTE,             CREATE_DATE,             UPDATE_DATE ) VALUES(     '2023-09-12',     '1',     '13:53:52',     '40TR0001.CSV',     '2023-09-12 13:53:52',     'False',     'リモート サーバーがエラーを返しました: (421) サービスが使用できません。管理接続を閉じています',     '2023/09/12 13:53:52',     '2023/09/12 13:53:52' )
【Date】2023/09/13 14:27:21【Exe】ConsoleApp_Download.exe【Source】Module_Download【Method】InsertTRNLOG【Description】SQL実行時エラー: INSERT INTO TRN_LOG(             PROCESS_DATE,             MACHINE_NO,             PROCESS_TIME,             FILE_NAME,             ACHIEVEMENT_RECEIVE_TIME,             ACHIEVEMENT_RESULT,             NOTE,             CREATE_DATE,             UPDATE_DATE ) VALUES(     '2023-09-13',     '1',     '14:27:21.21',     '40TR0001.CSV',     '2023-09-13 14:27:21.21',     '',     'パス 'C:\Users\1233\Desktop\remote-repo\KANSAI_ISHIDA_SANPAI\ソース\WindowsApp2\ConsoleApp_Download\bin\Debug\1\40TR0001.CSV' の一部が見つかりませんでした。',     '2023/09/13 14:27:21',     '2023/09/13 14:27:21' )
【Date】2023/09/13 14:33:57【Exe】ConsoleApp_Download.exe【Source】Module_Download【Method】InsertTRNLOG【Description】SQL実行時エラー: INSERT INTO TRN_LOG(             PROCESS_DATE,             MACHINE_NO,             PROCESS_TIME,             FILE_NAME,             ACHIEVEMENT_RECEIVE_TIME,             ACHIEVEMENT_RESULT,             NOTE,             CREATE_DATE,             UPDATE_DATE ) VALUES(     '2023-09-13',     '1',     '14:33:57.57',     '40TR0001.CSV',     '2023-09-13 14:33:57.57',     '',     'パス 'C:\Users\1233\Desktop\remote-repo\KANSAI_ISHIDA_SANPAI\ソース\WindowsApp2\ConsoleApp_Download\bin\Debug\1\40TR0001.CSV' の一部が見つかりませんでした。',     '2023/09/13 14:33:57',     '2023/09/13 14:33:57' )
【Date】2023/09/14 14:26:56【Exe】ConsoleApp_Download.exe【Source】Module_Download【Method】DelUploadFtp【Description】ファイル 'C:\SANPAI_DX\FTP_DELETE\40TR0002.DEL' が見つかりませんでした。
